[package]
name = "ezkl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2023_02_02"}
halo2curves = { git = 'https://github.com/privacy-scaling-explorations/halo2curves', tag = "0.3.1" }
rand = "0.8"
itertools = "0.10.3"
tensorflow = {version = "0.18.0", features = ["eager"], optional = true }
plotters = { version = "0.3.0", optional = true }
tract-onnx = { version = "0.17.7", optional = true }
anyhow = "1.0.65"
clap = { version = "4.0.32", features = ["derive"] }
serde = { version = "1.0.126", features = ["derive"], optional = true  }
serde_json = { version = "1.0.64", optional = true }
log = { version = "0.4.17", optional = true }
tabled = { version = "0.9.0", optional = true}
colog = { version = "1.1.0", optional = true }
eq-float = "0.1.0"
thiserror = "1.0.38"
hex = "0.4.3"
ethereum_types = { package = "ethereum-types", version = "0.14.1", default-features = false, features = ["std"]}
halo2_wrong_ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", package = "ecc", tag = "v2023_02_02"}
snark-verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier", tag = "v2023_02_02"}
# evm related deps
ethers = "1.0.2"
ethers-solc = "1.0.2"
tokio = { version = "1.22.0", features = ["macros"] }

[dev-dependencies]
criterion = {version = "0.3",  features = ["html_reports"]}
tempfile = "3.3.0"
reqwest = "0.11.14"
lazy_static = "1.4.0"
mnist = "0.5"
seq-macro = "0.3.1"
test-case = "2.2.2"
ctor = "0.1.26"

[[bench]]
name = "affine"
harness = false

[[bench]]
name = "cnvrl"
harness = false

[[bench]]
name = "relu"
harness = false

[[bench]]
name = "range"
harness = false

[[bin]]
name = "ezkl"
test = false
bench = false
required-features = ["ezkl"]

[features]
default = ["ezkl"]
render = ["halo2_proofs/dev-graph", "plotters"]
tensorflow = ["dep:tensorflow"]
onnx = ["dep:tract-onnx"]
ezkl = ["onnx", "serde", "serde_json", "log", "colog", "tabled"]
